# Generated by Django 3.2.8 on 2021-10-25 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 10, 25, 14, 52, 32, 912397, tzinfo=utc)),
        ),
    ]
