# Generated by Django 3.2.8 on 2021-10-25 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 10, 25, 14, 53, 18, 499691, tzinfo=utc)),
        ),
    ]
